name: ShopDB
version: 1.0
author: moderator_man
main: net.oldschoolminecraft.shopdb.ShopDB
commands:
  runshopindex:
    description: Indexes chest shops in predefined regions
    permission: shopdb.runindex
    default: op
  sdbr:
    description: Reload ShopDB configuration
    permission: shopdb.reload
    default: op
  testchunkindex:
    description: Test chunk index
    permission: shopdb.runindex
    default: op